from rest_framework import generics, permissions, filters
from drf_api.permissions import IsNotificationOwner
from .models import Notification
from .serializers import NotificationSerializer


class NotificationList(generics.ListAPIView):
    """
Fetches and lists all notifications for a user. This method is designed solely for the retrieval of notifications, as they are generated by the system based on specific triggers or events. No functionality is provided to manually create notifications through this interface, reflecting the automated nature of notification generation.

Returns:
    A list of notification objects, each containing details about the notification such as the type, message, and timestamp. If no notifications are available, an empty list is returned.
"""

    serializer_class = NotificationSerializer

    permission_classes = [permissions.IsAuthenticated]

    filter_backends = [filters.OrderingFilter]
    ordering_fields = ["created_at", "is_read"]
    

    def get_queryset(self):
        return Notification.objects.filter(owner=self.request.user)

    def perform_create(self, serializer):
        serializer.save(owner=self.request.user)


class NotificationDetail(generics.RetrieveUpdateDestroyAPIView):
    """Retrieves or deletes a notification by its ID, accessible only to the notification's owner..
    """

    queryset = Notification.objects.all()
    serializer_class = NotificationSerializer
    permission_classes = [permissions.IsAuthenticated, IsNotificationOwner]