# Generated by Django 3.2.24 on 2024-05-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='admission_price',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
