# Generated by Django 3.2.24 on 2024-05-03 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20240503_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='admission_price',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='website',
        ),
    ]
