# Generated by Django 3.2.24 on 2024-05-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='admission_price',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
